### ISSUE TITLE
trouble getting it to work

### ISSUE THREAD

**Issue by srrvnn** [ashish1294/code-now#22]
i forked and tried to install this last night, and i have been unsuccessful. 
1. the install from chrome web store doesn't have the fix for code chef. so i installed from the source
2. subprocess.Popen fails with [Errno 2], for subl and a valid absolute file path. i ran the Popen command  with the same params from the shell, and from a test file. they work. 
3. the connectNative port disconnects as soon as the error happens. 
4. i added shell=True to the subprocess.Popen command. this time i see the subprocess was started message, but it does not.
5. and then the connectNative port disconnects

all this on py 2.7.10. what am i missing?

**Comment by ashish1294** [comment]
Yes. Chrome Store is outdated. Will fix it soon.

Can you post the traceback of [errno 2] ?

**Comment by srrvnn** [comment]
is there a way i can see logs from prog.py, apart from sending them across using send_message, and seeing them in the console of the background page? sending traceback.format_exc() via send_message prints this on the console 

```
(BLESSED_EXTENSION context for fjckpcemnanimklmcibopkciaflakfeg) undefined:1: Uncaught        SyntaxError: Unexpected token 
{SyntaxError: Unexpected token 

    at Object.parse (native)
    at dispatchOnMessage (extensions::messaging:309:21)}

```

but, i am guessing that's not useful.

**Comment by ashish1294** [comment]
A good way to see the log is by starting chromium browser via command line
and enabling logging by passing appropriate option. Any error raised by
prog.py is printed on the terminal itself.

It works with chromium only. For Chrome you have to check the log file
which is tedius.

**Comment by srrvnn** [comment]
SOLVED. 

i installed chromium, and the extension worked on chromium that i launched via the command line like so `/Applications/Chromium.app/Content/MacOS/Chromium`. so i ran chrome via command line in the same way and it worked. for some reason the chrome i had earlier on my dock didn't have permissions (?) to open subl, it was able to create the solution files nonetheless.  

next on to some enhancements..

**Comment by ashish1294** [comment]
Great !

**Comment by srrvnn** [comment]
darn. problem still persists. i can open subl properly only if i launch chrome from the terminal, subsequent launches from the dock don't work well. more info [in this superuser question](http://superuser.com/questions/1045106/google-chrome-cannot-connect-to-native-message-process-host-after-docking).

seen anything like this?

**Comment by ashish1294** [comment]
I just tried doing it. I launched chrome from dock and tried opening the text editors. It worked well for me.

It might be machine specific problem, or it may be some other problem which we are unable to notice. Without knowing the error log, it's difficult to guess the problem.

**Comment by ashish1294** [comment]
Did you reinstall the host program / plugin between the launch from terminal and launch from dock ?
